name: VisualControl
main: me.locksmyth.visualcontrol.VisualControl
version: 0.1.2
depend: [Spout]
softdepend: [StyxSpace, Sphereworld]
description: Multiworld control over world visual aesthetics. Including unique texture packs, sun, moon, star and cloud details.
commands:
    vcset:
        description: Set a configuration option.
        permission: vcset
        usage: |
            /<command> [sun|moon|stars|clouds|use] [on|off|default|<level>|<URL>]
    vcupdate:
        description: Update a players visuals.
        permission: vcupdate
        usage: |
            /<command> [player]
    vcreload:
        description: Reloads the configuration file.
        permission: vcreload
        usage: |
            /<command>
permissions:
    vcset.*:
        description: Gives access to all vcset commands
        children:
            vcset.sun: true
            vcset.moon: true
            vcset.clouds: true
            vcset.use: true
    vcset.sun:
        description: Allows manipulation of the sun
        vcset: op
    vcset.moon:
        description: Allows manipulation of the moon 
        vcset: op
    vcset.clouds:
        description: Allows manipulation of the clouds
        vcset: op
    vcset.use:
        description: Allows manipulation of the texture packs
        vcset: op